# Generated by Django 4.2 on 2023-04-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrateurs',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrateurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidatures',
            fields=[
                ('id_cand', models.AutoField(primary_key=True, serialize=False)),
                ('date_cand', models.DateField(blank=True, null=True)),
                ('statut_cand', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'candidatures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diplomes',
            fields=[
                ('id_dipl', models.AutoField(primary_key=True, serialize=False)),
                ('lib_dipl', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'diplomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaines',
            fields=[
                ('id_dom', models.AutoField(primary_key=True, serialize=False)),
                ('lib_dom', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'domaines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entreprises',
            fields=[
                ('id_ent', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ent', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'entreprises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiants',
            fields=[
                ('id_etu', models.AutoField(primary_key=True, serialize=False)),
                ('cv', models.BinaryField(blank=True, null=True)),
                ('lm', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etudiants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metiers',
            fields=[
                ('id_metier', models.AutoField(primary_key=True, serialize=False)),
                ('lib_metier', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_metier', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'metiers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffreStage',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('desc_stage', models.CharField(blank=True, max_length=1500, null=True)),
                ('duree', models.CharField(blank=True, max_length=25, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_pub', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=20, null=True)),
                ('localisation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'offre_stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profils',
            fields=[
                ('id_profil', models.AutoField(primary_key=True, serialize=False)),
                ('lib_profil', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'profils',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secteurs',
            fields=[
                ('id_sec', models.AutoField(primary_key=True, serialize=False)),
                ('lib_sec', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'secteurs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Statuts',
            fields=[
                ('id_statut', models.AutoField(primary_key=True, serialize=False)),
                ('lib_statut', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'statuts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=25, null=True)),
                ('prenom', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('num_tel', models.CharField(blank=True, max_length=15, null=True)),
                ('num_voie', models.CharField(blank=True, max_length=10, null=True)),
                ('nom_voie', models.CharField(blank=True, max_length=40, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('commune', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': False,
            },
        ),
    ]
